In [1]:
import numpy as np
import pandas as pd
from ydata_profiling import ProfileReport

/tmp/ipykernel_2766/1940793455.py:3: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [2]:
pd.set_option('display.max_columns',None)

In [4]:
df=pd.read_csv("~/Machine Learning/EDA/Project/stops.csv")

/tmp/ipykernel_2766/1506875383.py:1: DtypeWarning: Columns (9,10,16,17,18,19,21,25,26,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("~/Machine Learning/EDA/Project/stops.csv")

In [5]:
df

,Unnamed: 0,location,lat,lng,geocode_source,subject_age,subject_race,subject_sex,officer_age,officer_race,officer_sex,officer_years_of_service,type,violation,arrest_made,citation_issued,outcome,contraband_found,contraband_drugs,contraband_weapons,contraband_alcohol,contraband_other,search_conducted,search_person,search_vehicle,vehicle_make,vehicle_model,raw_race,raw_driver_race,datetime
0,0,700 LINCOLN W,41.874405,-88.216690,SU,23.0,black,male,NaN,white,male,17.0,vehicular,DRIVING ON SUSPENDED LICENSE,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,BLACK,NaN,2012-01-06 09:00:00
1,1,NaN,NaN,NaN,NaN,23.0,hispanic,male,NaN,white,male,2.0,vehicular,DRIVING/NEVER ISSUED LICENSE,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,HISPANIC,NaN,2012-01-01 00:00:00
2,2,0 NORTHWEST HWY & HILLSIDE RD S,42.146703,-88.119549,SU,38.0,white,female,NaN,NaN,NaN,NaN,vehicular,DRIVING ON SUSPENDED LICENSE,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,WHITE,NaN,2012-01-01 01:00:00
3,3,108 LAMON AVE N,41.882072,-87.747829,SU,35.0,black,male,34.0,black,male,8.0,vehicular,IVC - FAIL TO STOP/SIGNAL CROSSWALK,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,BLACK,NaN,2012-01-01 01:00:00
4,4,3451 177TH ST W,41.567987,-87.701027,SU,20.0,black,male,NaN,NaN,NaN,NaN,vehicular,IVC - DRIVING 15-20 MPH ABOVE SPEED LIMIT,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,BLACK,NaN,2012-01-01 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2091115,2108093,37XX W MONTROSE AVE,41.959602,-87.824398,SU,39.0,black,male,NaN,NaN,NaN,NaN,vehicular,DOUBLE PARKING/NO STANDING,False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,CHEVROLET,EQUINOX,BLACK,NaN,2020-05-16 23:38:00
2091116,2108094,60XX S STATE ST,41.881017,-87.627817,SU,34.0,black,female,NaN,NaN,NaN,NaN,vehicular,"LIGHT, TAIL LIGHTS REQUIRED",False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,NISSAN,SENTRA,BLACK,NaN,2020-05-16 23:40:00
2091117,2108095,26XX S STATE ST,41.881212,-87.628180,SU,31.0,black,male,NaN,NaN,NaN,NaN,vehicular,SPEED LIMIT 30MPH STR/15MPH ALLEY,False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,CHRYSLER/300,CHRYSLER/300,BLACK,NaN,2020-05-16 23:40:00
2091118,2108096,44XX N SAWYER AVE,41.898274,-87.707719,SU,44.0,hispanic,female,NaN,NaN,NaN,NaN,vehicular,HEADLIGHT TWO REQUIRED-MOTOR VEHICLE,False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,CHEVROLET,EXPRESS,HISPANIC,NaN,2020-05-16 23:47:00
2091119,2108097,18XX W AUGUSTA BLVD,41.899760,-87.664197,SU,47.0,hispanic,female,NaN,NaN,NaN,NaN,vehicular,BROKEN/INOPERABLE LAMPS,False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,TOYOTA,CAMRY,HISPANIC,NaN,2020-05-16 23:50:00

In [20]:
profile=ProfileReport(df)

In [21]:
profile.to_file('stops')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|                                                   | 0/35 [00:00<?, ?it/s]
  3%|█▏                                         | 1/35 [00:16<08:35, 15.16s/it]
  6%|██▍                                        | 2/35 [00:16<03:48,  6.94s/it]
  9%|███▋                                       | 3/35 [00:17<02:10,  4.09s/it]
 11%|████▉                                      | 4/35 [00:18<01:34,  3.04s/it]
 14%|██████▏                                    | 5/35 [00:19<01:09,  2.31s/it]
 17%|███████▎                                   | 6/35 [00:21<00:56,  1.93s/it]
 20%|████████▌                                  | 7/35 [00:22<00:48,  1.72s/it]
 23%|█████████▊                                 | 8/35 [00:24<00:45,  1.68s/it]
 26%|███████████                                | 9/35 [00:25<00:39,  1.53s/it]
 29%|████████████                              | 10/35 [00:25<00:32,  1.31s/it]
 31%|█████████████▏                            | 11/35 [00:27<00:33,  1.40s/it]
 34%|██████████████▍                           | 12/35 [00:29<00:35,  1.54s/it]
 37%|███████████████▌                          | 13/35 [00:35<01:02,  2.83s/it]
 40%|████████████████▊                         | 14/35 [00:36<00:50,  2.42s/it]
 43%|██████████████████                        | 15/35 [00:36<00:36,  1.81s/it]
 46%|███████████████████▏                      | 16/35 [00:38<00:36,  1.92s/it]
 49%|████████████████████▍                     | 17/35 [00:41<00:34,  1.94s/it]
 51%|█████████████████████▌                    | 18/35 [00:44<00:40,  2.40s/it]
 54%|██████████████████████▊                   | 19/35 [00:45<00:31,  1.99s/it]
 57%|████████████████████████                  | 20/35 [00:50<00:41,  2.75s/it]
 60%|█████████████████████████▏                | 21/35 [00:51<00:29,  2.13s/it]
 63%|██████████████████████████▍               | 22/35 [00:52<00:23,  1.83s/it]
 66%|███████████████████████████▌              | 23/35 [00:53<00:22,  1.84s/it]
 69%|████████████████████████████▊             | 24/35 [00:53<00:14,  1.35s/it]
 71%|██████████████████████████████            | 25/35 [00:54<00:10,  1.08s/it]
 74%|███████████████████████████████▏          | 26/35 [00:54<00:08,  1.06it/s]
 77%|████████████████████████████████▍         | 27/35 [00:55<00:05,  1.43it/s]
100%|██████████████████████████████████████████| 35/35 [00:55<00:00,  1.58s/it]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

/home/ammarkhalid/anaconda3/lib/python3.13/site-packages/ydata_profiling/profile_report.py:386: UserWarning: Extension  not supported. For now we assume .html was intended. To remove this warning, please use .html or .json.
  warnings.warn(

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2108098 entries, 0 to 2108097
Data columns (total 34 columns):
 #   Column                    Dtype
---  ------                    -----
 0   date                      object
 1   time                      object
 2   location                  object
 3   lat                       float64
 4   lng                       float64
 5   geocode_source            object
 6   beat                      float64
 7   district                  float64
 8   subject_age               float64
 9   subject_race              object
 10  subject_sex               object
 11  officer_id_hash           object
 12  officer_age               float64
 13  officer_race              object
 14  officer_sex               object
 15  officer_years_of_service  float64
 16  unit                      float64
 17  type                      object
 18  violation                 object
 19  arrest_made               bool
 20  citation_issued           bool
 21  outcome                   object
 22  contraband_found          object
 23  contraband_drugs          object
 24  contraband_weapons        object
 25  contraband_alcohol        bool
 26  contraband_other          object
 27  search_conducted          bool
 28  search_person             bool
 29  search_vehicle            bool
 30  vehicle_make              object
 31  vehicle_model             object
 32  raw_race                  object
 33  raw_driver_race           object
dtypes: bool(6), float64(8), object(20)
memory usage: 462.4+ MB

In [6]:
df.isnull().sum()

Unnamed: 0                        0
location                      74981
lat                          105265
lng                          105265
geocode_source               105265
subject_age                  624048
subject_race                 652137
subject_sex                     851
officer_age                 2031913
officer_race                1318422
officer_sex                 1318422
officer_years_of_service    1320884
type                              1
violation                         1
arrest_made                       0
citation_issued                   0
outcome                     1258983
contraband_found            2078938
contraband_drugs            2078938
contraband_weapons          2078938
contraband_alcohol                0
contraband_other            2078938
search_conducted                  0
search_person                     0
search_vehicle                    0
vehicle_make                 832137
vehicle_model                832137
raw_race                     621918
raw_driver_race             2079272
datetime                          0
dtype: int64

In [7]:
df.shape

(2091120, 30)

In [40]:
# first of all drop the identifier
df.drop(columns='raw_row_number',inplace=True)

In [25]:
df

,date,time,location,lat,lng,geocode_source,beat,district,subject_age,subject_race,subject_sex,officer_id_hash,officer_age,officer_race,officer_sex,officer_years_of_service,unit,type,violation,arrest_made,citation_issued,outcome,contraband_found,contraband_drugs,contraband_weapons,contraband_alcohol,contraband_other,search_conducted,search_person,search_vehicle,vehicle_make,vehicle_model,raw_race,raw_driver_race
0,2012-01-06,09:00:00,700 LINCOLN W,41.874405,-88.216690,SU,NaN,NaN,23.0,black,male,a6d791f976,NaN,white,male,17.0,NaN,vehicular,DRIVING ON SUSPENDED LICENSE,True,NaN,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,BLACK,NaN
1,2012-01-01,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,23.0,hispanic,male,81da9fab7e,NaN,white,male,2.0,NaN,vehicular,DRIVING/NEVER ISSUED LICENSE,True,NaN,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,HISPANIC,NaN
2,2012-01-01,01:00:00,0 NORTHWEST HWY & HILLSIDE RD S,42.146703,-88.119549,SU,NaN,NaN,38.0,white,female,NaN,NaN,NaN,NaN,NaN,NaN,vehicular,DRIVING ON SUSPENDED LICENSE,True,NaN,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,WHITE,NaN
3,2012-01-01,01:00:00,108 LAMON AVE N,41.882072,-87.747829,SU,NaN,NaN,35.0,black,male,048359e7c8,34.0,black,male,8.0,NaN,vehicular,IVC - FAIL TO STOP/SIGNAL CROSSWALK,True,NaN,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,BLACK,NaN
4,2012-01-01,01:00:00,3451 177TH ST W,41.567987,-87.701027,SU,NaN,NaN,20.0,black,male,NaN,NaN,NaN,NaN,NaN,NaN,vehicular,IVC - DRIVING 15-20 MPH ABOVE SPEED LIMIT,True,NaN,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,BLACK,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2108093,2020-05-16,23:38:00,37XX W MONTROSE AVE,41.959602,-87.824398,SU,1723.0,17.0,39.0,black,male,NaN,NaN,NaN,NaN,NaN,215.0,vehicular,DOUBLE PARKING/NO STANDING,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,False,False,CHEVROLET,EQUINOX,BLACK,NaN
2108094,2020-05-16,23:40:00,60XX S STATE ST,41.881017,-87.627817,SU,311.0,3.0,34.0,black,female,NaN,NaN,NaN,NaN,NaN,3.0,vehicular,"LIGHT, TAIL LIGHTS REQUIRED",NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,False,False,NISSAN,SENTRA,BLACK,NaN
2108095,2020-05-16,23:40:00,26XX S STATE ST,41.881212,-87.628180,SU,133.0,1.0,31.0,black,male,NaN,NaN,NaN,NaN,NaN,1.0,vehicular,SPEED LIMIT 30MPH STR/15MPH ALLEY,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,False,False,CHRYSLER/300,CHRYSLER/300,BLACK,NaN
2108096,2020-05-16,23:47:00,44XX N SAWYER AVE,41.898274,-87.707719,SU,1724.0,17.0,44.0,hispanic,female,NaN,NaN,NaN,NaN,NaN,215.0,vehicular,HEADLIGHT TWO REQUIRED-MOTOR VEHICLE,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,False,False,CHEVROLET,EXPRESS,HISPANIC,NaN
2108097,2020-05-16,23:50:00,18XX W AUGUSTA BLVD,41.899760,-87.664197,SU,1212.0,12.0,47.0,hispanic,female,NaN,NaN,NaN,NaN,NaN,12.0,vehicular,BROKEN/INOPERABLE LAMPS,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,False,False,False,TOYOTA,CAMRY,HISPANIC,NaN

In [41]:
# we will first handle the constant values
#In police stop datasets, officers typically only check the box if an arrest was actually made or a citation was issued. 
#If they let the driver go with a warning, they simply leave it blank. 
#This means we can reasonably assume that a missing value (NaN) actually means False.
#If no contraband was found, the officer didn't log anything.  
cols=['arrest_made','citation_issued']
for col in cols:
    df[col]=df[col].fillna(False)
df

/tmp/ipykernel_2424/2559760276.py:8: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df[col]=df[col].fillna(False)

,date,time,location,lat,lng,geocode_source,beat,district,subject_age,subject_race,subject_sex,officer_id_hash,officer_age,officer_race,officer_sex,officer_years_of_service,unit,type,violation,arrest_made,citation_issued,outcome,contraband_found,contraband_drugs,contraband_weapons,contraband_alcohol,contraband_other,search_conducted,search_person,search_vehicle,vehicle_make,vehicle_model,raw_race,raw_driver_race
0,2012-01-06,09:00:00,700 LINCOLN W,41.874405,-88.216690,SU,NaN,NaN,23.0,black,male,a6d791f976,NaN,white,male,17.0,NaN,vehicular,DRIVING ON SUSPENDED LICENSE,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,BLACK,NaN
1,2012-01-01,00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,23.0,hispanic,male,81da9fab7e,NaN,white,male,2.0,NaN,vehicular,DRIVING/NEVER ISSUED LICENSE,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,HISPANIC,NaN
2,2012-01-01,01:00:00,0 NORTHWEST HWY & HILLSIDE RD S,42.146703,-88.119549,SU,NaN,NaN,38.0,white,female,NaN,NaN,NaN,NaN,NaN,NaN,vehicular,DRIVING ON SUSPENDED LICENSE,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,WHITE,NaN
3,2012-01-01,01:00:00,108 LAMON AVE N,41.882072,-87.747829,SU,NaN,NaN,35.0,black,male,048359e7c8,34.0,black,male,8.0,NaN,vehicular,IVC - FAIL TO STOP/SIGNAL CROSSWALK,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,BLACK,NaN
4,2012-01-01,01:00:00,3451 177TH ST W,41.567987,-87.701027,SU,NaN,NaN,20.0,black,male,NaN,NaN,NaN,NaN,NaN,NaN,vehicular,IVC - DRIVING 15-20 MPH ABOVE SPEED LIMIT,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,BLACK,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2108093,2020-05-16,23:38:00,37XX W MONTROSE AVE,41.959602,-87.824398,SU,1723.0,17.0,39.0,black,male,NaN,NaN,NaN,NaN,NaN,215.0,vehicular,DOUBLE PARKING/NO STANDING,False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,CHEVROLET,EQUINOX,BLACK,NaN
2108094,2020-05-16,23:40:00,60XX S STATE ST,41.881017,-87.627817,SU,311.0,3.0,34.0,black,female,NaN,NaN,NaN,NaN,NaN,3.0,vehicular,"LIGHT, TAIL LIGHTS REQUIRED",False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,NISSAN,SENTRA,BLACK,NaN
2108095,2020-05-16,23:40:00,26XX S STATE ST,41.881212,-87.628180,SU,133.0,1.0,31.0,black,male,NaN,NaN,NaN,NaN,NaN,1.0,vehicular,SPEED LIMIT 30MPH STR/15MPH ALLEY,False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,CHRYSLER/300,CHRYSLER/300,BLACK,NaN
2108096,2020-05-16,23:47:00,44XX N SAWYER AVE,41.898274,-87.707719,SU,1724.0,17.0,44.0,hispanic,female,NaN,NaN,NaN,NaN,NaN,215.0,vehicular,HEADLIGHT TWO REQUIRED-MOTOR VEHICLE,False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,CHEVROLET,EXPRESS,HISPANIC,NaN
2108097,2020-05-16,23:50:00,18XX W AUGUSTA BLVD,41.899760,-87.664197,SU,1212.0,12.0,47.0,hispanic,female,NaN,NaN,NaN,NaN,NaN,12.0,vehicular,BROKEN/INOPERABLE LAMPS,False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,TOYOTA,CAMRY,HISPANIC,NaN

In [42]:
contraband_cols = [
    'contraband_found', 'contraband_drugs', 
    'contraband_weapons', 'contraband_alcohol', 'contraband_other'
]

# Cast to Pandas nullable boolean so they hold True, False, and pd.NA natively
df[contraband_cols] = df[contraband_cols].astype('boolean')

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2108098 entries, 0 to 2108097
Data columns (total 34 columns):
 #   Column                    Dtype
---  ------                    -----
 0   date                      object
 1   time                      object
 2   location                  object
 3   lat                       float64
 4   lng                       float64
 5   geocode_source            object
 6   beat                      float64
 7   district                  float64
 8   subject_age               float64
 9   subject_race              object
 10  subject_sex               object
 11  officer_id_hash           object
 12  officer_age               float64
 13  officer_race              object
 14  officer_sex               object
 15  officer_years_of_service  float64
 16  unit                      float64
 17  type                      object
 18  violation                 object
 19  arrest_made               bool
 20  citation_issued           bool
 21  outcome                   object
 22  contraband_found          boolean
 23  contraband_drugs          boolean
 24  contraband_weapons        boolean
 25  contraband_alcohol        boolean
 26  contraband_other          boolean
 27  search_conducted          bool
 28  search_person             bool
 29  search_vehicle            bool
 30  vehicle_make              object
 31  vehicle_model             object
 32  raw_race                  object
 33  raw_driver_race           object
dtypes: bool(5), boolean(5), float64(8), object(16)
memory usage: 416.2+ MB

In [44]:
df['datetime']=pd.to_datetime(df['date'].astype(str) + " "+df['time'].astype(str),errors='coerce')
df.drop(columns=['date','time'],inplace=True)

In [94]:
df

,location,lat,lng,geocode_source,beat,district,subject_age,subject_race,subject_sex,officer_id_hash,officer_age,officer_race,officer_sex,officer_years_of_service,unit,type,violation,arrest_made,citation_issued,outcome,contraband_found,contraband_drugs,contraband_weapons,contraband_alcohol,contraband_other,search_conducted,search_person,search_vehicle,vehicle_make,vehicle_model,raw_race,raw_driver_race,datetime
0,700 LINCOLN W,41.874405,-88.216690,SU,NaN,NaN,23.0,black,male,a6d791f976,NaN,white,male,17.0,NaN,vehicular,DRIVING ON SUSPENDED LICENSE,True,False,arrest,<NA>,<NA>,<NA>,False,<NA>,False,False,False,NaN,NaN,BLACK,NaN,2012-01-06 09:00:00
1,NaN,NaN,NaN,NaN,NaN,NaN,23.0,hispanic,male,81da9fab7e,NaN,white,male,2.0,NaN,vehicular,DRIVING/NEVER ISSUED LICENSE,True,False,arrest,<NA>,<NA>,<NA>,False,<NA>,False,False,False,NaN,NaN,HISPANIC,NaN,2012-01-01 00:00:00
2,0 NORTHWEST HWY & HILLSIDE RD S,42.146703,-88.119549,SU,NaN,NaN,38.0,white,female,NaN,NaN,NaN,NaN,NaN,NaN,vehicular,DRIVING ON SUSPENDED LICENSE,True,False,arrest,<NA>,<NA>,<NA>,False,<NA>,False,False,False,NaN,NaN,WHITE,NaN,2012-01-01 01:00:00
3,108 LAMON AVE N,41.882072,-87.747829,SU,NaN,NaN,35.0,black,male,048359e7c8,34.0,black,male,8.0,NaN,vehicular,IVC - FAIL TO STOP/SIGNAL CROSSWALK,True,False,arrest,<NA>,<NA>,<NA>,False,<NA>,False,False,False,NaN,NaN,BLACK,NaN,2012-01-01 01:00:00
4,3451 177TH ST W,41.567987,-87.701027,SU,NaN,NaN,20.0,black,male,NaN,NaN,NaN,NaN,NaN,NaN,vehicular,IVC - DRIVING 15-20 MPH ABOVE SPEED LIMIT,True,False,arrest,<NA>,<NA>,<NA>,False,<NA>,False,False,False,NaN,NaN,BLACK,NaN,2012-01-01 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2108093,37XX W MONTROSE AVE,41.959602,-87.824398,SU,1723.0,17.0,39.0,black,male,NaN,NaN,NaN,NaN,NaN,215.0,vehicular,DOUBLE PARKING/NO STANDING,False,False,NaN,<NA>,<NA>,<NA>,False,<NA>,False,False,False,CHEVROLET,EQUINOX,BLACK,NaN,2020-05-16 23:38:00
2108094,60XX S STATE ST,41.881017,-87.627817,SU,311.0,3.0,34.0,black,female,NaN,NaN,NaN,NaN,NaN,3.0,vehicular,"LIGHT, TAIL LIGHTS REQUIRED",False,False,NaN,<NA>,<NA>,<NA>,False,<NA>,False,False,False,NISSAN,SENTRA,BLACK,NaN,2020-05-16 23:40:00
2108095,26XX S STATE ST,41.881212,-87.628180,SU,133.0,1.0,31.0,black,male,NaN,NaN,NaN,NaN,NaN,1.0,vehicular,SPEED LIMIT 30MPH STR/15MPH ALLEY,False,False,NaN,<NA>,<NA>,<NA>,False,<NA>,False,False,False,CHRYSLER/300,CHRYSLER/300,BLACK,NaN,2020-05-16 23:40:00
2108096,44XX N SAWYER AVE,41.898274,-87.707719,SU,1724.0,17.0,44.0,hispanic,female,NaN,NaN,NaN,NaN,NaN,215.0,vehicular,HEADLIGHT TWO REQUIRED-MOTOR VEHICLE,False,False,NaN,<NA>,<NA>,<NA>,False,<NA>,False,False,False,CHEVROLET,EXPRESS,HISPANIC,NaN,2020-05-16 23:47:00
2108097,18XX W AUGUSTA BLVD,41.899760,-87.664197,SU,1212.0,12.0,47.0,hispanic,female,NaN,NaN,NaN,NaN,NaN,12.0,vehicular,BROKEN/INOPERABLE LAMPS,False,False,NaN,<NA>,<NA>,<NA>,False,<NA>,False,False,False,TOYOTA,CAMRY,HISPANIC,NaN,2020-05-16 23:50:00

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2108098 entries, 0 to 2108097
Data columns (total 33 columns):
 #   Column                    Dtype
---  ------                    -----
 0   location                  object
 1   lat                       float64
 2   lng                       float64
 3   geocode_source            object
 4   beat                      float64
 5   district                  float64
 6   subject_age               float64
 7   subject_race              object
 8   subject_sex               object
 9   officer_id_hash           object
 10  officer_age               float64
 11  officer_race              object
 12  officer_sex               object
 13  officer_years_of_service  float64
 14  unit                      float64
 15  type                      object
 16  violation                 object
 17  arrest_made               bool
 18  citation_issued           bool
 19  outcome                   object
 20  contraband_found          boolean
 21  contraband_drugs          boolean
 22  contraband_weapons        boolean
 23  contraband_alcohol        boolean
 24  contraband_other          boolean
 25  search_conducted          bool
 26  search_person             bool
 27  search_vehicle            bool
 28  vehicle_make              object
 29  vehicle_model             object
 30  raw_race                  object
 31  raw_driver_race           object
 32  datetime                  datetime64[ns]
dtypes: bool(5), boolean(5), datetime64[ns](1), float64(8), object(14)
memory usage: 400.1+ MB

In [46]:
df.drop(columns=['district','unit','beat'],inplace=True)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2108098 entries, 0 to 2108097
Data columns (total 30 columns):
 #   Column                    Dtype
---  ------                    -----
 0   location                  object
 1   lat                       float64
 2   lng                       float64
 3   geocode_source            object
 4   subject_age               float64
 5   subject_race              object
 6   subject_sex               object
 7   officer_id_hash           object
 8   officer_age               float64
 9   officer_race              object
 10  officer_sex               object
 11  officer_years_of_service  float64
 12  type                      object
 13  violation                 object
 14  arrest_made               bool
 15  citation_issued           bool
 16  outcome                   object
 17  contraband_found          boolean
 18  contraband_drugs          boolean
 19  contraband_weapons        boolean
 20  contraband_alcohol        boolean
 21  contraband_other          boolean
 22  search_conducted          bool
 23  search_person             bool
 24  search_vehicle            bool
 25  vehicle_make              object
 26  vehicle_model             object
 27  raw_race                  object
 28  raw_driver_race           object
 29  datetime                  datetime64[ns]
dtypes: bool(5), boolean(5), datetime64[ns](1), float64(5), object(14)
memory usage: 351.8+ MB

In [ ]:
profile=ProfileReport(df)

In [100]:
profile.to_file('stops.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|                                                   | 0/30 [00:00<?, ?it/s]
  3%|█▍                                         | 1/30 [00:29<13:30, 27.95s/it]
  7%|██▊                                        | 2/30 [00:30<06:02, 12.94s/it]
 10%|████▎                                      | 3/30 [00:31<03:12,  7.14s/it]
 13%|█████▋                                     | 4/30 [00:32<02:04,  4.78s/it]
 17%|███████▏                                   | 5/30 [00:32<01:19,  3.20s/it]
 20%|████████▌                                  | 6/30 [00:33<00:56,  2.36s/it]
 23%|██████████                                 | 7/30 [00:34<00:38,  1.69s/it]
 27%|███████████▍                               | 8/30 [00:34<00:34,  1.56s/it]
 30%|████████████▉                              | 9/30 [00:35<00:25,  1.22s/it]
 33%|██████████████                            | 10/30 [00:40<00:28,  1.41s/it]
 37%|███████████████▍                          | 11/30 [00:41<00:43,  2.26s/it]
 40%|████████████████▊                         | 12/30 [00:42<00:36,  2.01s/it]
 43%|██████████████████▏                       | 13/30 [00:46<00:35,  2.08s/it]
 47%|███████████████████▌                      | 14/30 [00:47<00:35,  2.23s/it]
 50%|█████████████████████                     | 15/30 [00:48<00:29,  1.95s/it]
 53%|██████████████████████▍                   | 16/30 [00:50<00:22,  1.63s/it]
 57%|███████████████████████▊                  | 17/30 [00:50<00:18,  1.44s/it]
 60%|█████████████████████████▏                | 18/30 [00:51<00:15,  1.25s/it]
 63%|██████████████████████████▌               | 19/30 [00:51<00:10,  1.05it/s]
 93%|███████████████████████████████████████▏  | 28/30 [00:52<00:00,  3.52it/s]
100%|██████████████████████████████████████████| 30/30 [00:52<00:00,  1.76s/it]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [48]:
df.drop_duplicates(inplace=True)

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2091120 entries, 0 to 2108097
Data columns (total 30 columns):
 #   Column                    Dtype
---  ------                    -----
 0   location                  object
 1   lat                       float64
 2   lng                       float64
 3   geocode_source            object
 4   subject_age               float64
 5   subject_race              object
 6   subject_sex               object
 7   officer_id_hash           object
 8   officer_age               float64
 9   officer_race              object
 10  officer_sex               object
 11  officer_years_of_service  float64
 12  type                      object
 13  violation                 object
 14  arrest_made               bool
 15  citation_issued           bool
 16  outcome                   object
 17  contraband_found          boolean
 18  contraband_drugs          boolean
 19  contraband_weapons        boolean
 20  contraband_alcohol        boolean
 21  contraband_other          boolean
 22  search_conducted          bool
 23  search_person             bool
 24  search_vehicle            bool
 25  vehicle_make              object
 26  vehicle_model             object
 27  raw_race                  object
 28  raw_driver_race           object
 29  datetime                  datetime64[ns]
dtypes: bool(5), boolean(5), datetime64[ns](1), float64(5), object(14)
memory usage: 364.9+ MB

In [53]:
df['geocode_source']=df['geocode_source'].astype('category')
df['subject_race']=df['subject_race'].astype('category')
df['subject_sex']=df['subject_sex'].astype('category')
df['officer_race']=df['officer_race'].astype('category')
df['officer_sex']=df['officer_sex'].astype('category')
df['type']=df['type'].astype('category')
df['outcome']=df['outcome'].astype('category')
df['raw_race']=df['raw_race'].astype('category')
df['raw_driver_race']=df['raw_driver_race'].astype('category')

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2091120 entries, 0 to 2108097
Data columns (total 29 columns):
 #   Column                    Dtype
---  ------                    -----
 0   location                  object
 1   lat                       float64
 2   lng                       float64
 3   geocode_source            category
 4   subject_age               float64
 5   subject_race              category
 6   subject_sex               category
 7   officer_age               float64
 8   officer_race              category
 9   officer_sex               category
 10  officer_years_of_service  float64
 11  type                      category
 12  violation                 object
 13  arrest_made               bool
 14  citation_issued           bool
 15  outcome                   category
 16  contraband_found          boolean
 17  contraband_drugs          boolean
 18  contraband_weapons        boolean
 19  contraband_alcohol        boolean
 20  contraband_other          boolean
 21  search_conducted          bool
 22  search_person             bool
 23  search_vehicle            bool
 24  vehicle_make              object
 25  vehicle_model             object
 26  raw_race                  category
 27  raw_driver_race           category
 28  datetime                  datetime64[ns]
dtypes: bool(5), boolean(5), category(9), datetime64[ns](1), float64(5), object(4)
memory usage: 223.4+ MB

In [59]:
df = df.drop(columns=['officer_id_hash'])

In [62]:
df.to_csv('stops.csv')

In [63]:
profile=ProfileReport(df)
profile.to_file('stops.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|                                                   | 0/29 [00:00<?, ?it/s]
  3%|█▍                                         | 1/29 [00:24<11:34, 24.80s/it]
  7%|██▉                                        | 2/29 [00:25<04:41, 10.43s/it]
100%|██████████████████████████████████████████| 29/29 [00:25<00:00,  1.13it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

In [65]:
df=df.drop_duplicates()

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2091120 entries, 0 to 2091119
Data columns (total 30 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Unnamed: 0                int64
 1   location                  object
 2   lat                       float64
 3   lng                       float64
 4   geocode_source            object
 5   subject_age               float64
 6   subject_race              object
 7   subject_sex               object
 8   officer_age               float64
 9   officer_race              object
 10  officer_sex               object
 11  officer_years_of_service  float64
 12  type                      object
 13  violation                 object
 14  arrest_made               bool
 15  citation_issued           bool
 16  outcome                   object
 17  contraband_found          object
 18  contraband_drugs          object
 19  contraband_weapons        object
 20  contraband_alcohol        bool
 21  contraband_other          object
 22  search_conducted          bool
 23  search_person             bool
 24  search_vehicle            bool
 25  vehicle_make              object
 26  vehicle_model             object
 27  raw_race                  object
 28  raw_driver_race           object
 29  datetime                  object
dtypes: bool(6), float64(5), int64(1), object(18)
memory usage: 394.9+ MB

In [15]:
# Identify columns that should be categorical
cat_cols = ['outcome','type','geocode_source','subject_sex', 'subject_race', 'officer_race', 'officer_sex', 'violation', 'vehicle_make', 'vehicle_model']

# Convert them to category dtype
for col in cat_cols:
    if col in df.columns:
        df[col] = df[col].astype('category')

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2091120 entries, 0 to 2091119
Data columns (total 30 columns):
 #   Column                    Dtype
---  ------                    -----
 0   Unnamed: 0                int64
 1   location                  object
 2   lat                       float64
 3   lng                       float64
 4   geocode_source            category
 5   subject_age               float64
 6   subject_race              category
 7   subject_sex               category
 8   officer_age               float64
 9   officer_race              category
 10  officer_sex               category
 11  officer_years_of_service  float64
 12  type                      category
 13  violation                 category
 14  arrest_made               bool
 15  citation_issued           bool
 16  outcome                   category
 17  contraband_found          object
 18  contraband_drugs          object
 19  contraband_weapons        object
 20  contraband_alcohol        bool
 21  contraband_other          object
 22  search_conducted          bool
 23  search_person             bool
 24  search_vehicle            bool
 25  vehicle_make              category
 26  vehicle_model             category
 27  raw_race                  object
 28  raw_driver_race           object
 29  datetime                  object
dtypes: bool(6), category(10), float64(5), int64(1), object(8)
memory usage: 261.4+ MB

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2091120 entries, 0 to 2091119
Data columns (total 29 columns):
 #   Column                    Dtype
---  ------                    -----
 0   location                  object
 1   lat                       float64
 2   lng                       float64
 3   geocode_source            category
 4   subject_age               float64
 5   subject_race              category
 6   subject_sex               category
 7   officer_age               float64
 8   officer_race              category
 9   officer_sex               category
 10  officer_years_of_service  float64
 11  type                      category
 12  violation                 category
 13  arrest_made               bool
 14  citation_issued           bool
 15  outcome                   category
 16  contraband_found          object
 17  contraband_drugs          object
 18  contraband_weapons        object
 19  contraband_alcohol        bool
 20  contraband_other          object
 21  search_conducted          bool
 22  search_person             bool
 23  search_vehicle            bool
 24  vehicle_make              category
 25  vehicle_model             category
 26  raw_race                  object
 27  raw_driver_race           object
 28  datetime                  object
dtypes: bool(6), category(10), float64(5), object(8)
memory usage: 245.5+ MB

In [24]:
df=df.drop_duplicates()

In [25]:
df

,location,lat,lng,geocode_source,subject_age,subject_race,subject_sex,officer_age,officer_race,officer_sex,officer_years_of_service,type,violation,arrest_made,citation_issued,outcome,contraband_found,contraband_drugs,contraband_weapons,contraband_alcohol,contraband_other,search_conducted,search_person,search_vehicle,vehicle_make,vehicle_model,raw_race,raw_driver_race,datetime
0,700 LINCOLN W,41.874405,-88.216690,SU,23.0,black,male,NaN,white,male,17.0,vehicular,DRIVING ON SUSPENDED LICENSE,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,BLACK,NaN,2012-01-06 09:00:00
1,NaN,NaN,NaN,NaN,23.0,hispanic,male,NaN,white,male,2.0,vehicular,DRIVING/NEVER ISSUED LICENSE,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,HISPANIC,NaN,2012-01-01 00:00:00
2,0 NORTHWEST HWY & HILLSIDE RD S,42.146703,-88.119549,SU,38.0,white,female,NaN,NaN,NaN,NaN,vehicular,DRIVING ON SUSPENDED LICENSE,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,WHITE,NaN,2012-01-01 01:00:00
3,108 LAMON AVE N,41.882072,-87.747829,SU,35.0,black,male,34.0,black,male,8.0,vehicular,IVC - FAIL TO STOP/SIGNAL CROSSWALK,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,BLACK,NaN,2012-01-01 01:00:00
4,3451 177TH ST W,41.567987,-87.701027,SU,20.0,black,male,NaN,NaN,NaN,NaN,vehicular,IVC - DRIVING 15-20 MPH ABOVE SPEED LIMIT,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,BLACK,NaN,2012-01-01 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2091115,37XX W MONTROSE AVE,41.959602,-87.824398,SU,39.0,black,male,NaN,NaN,NaN,NaN,vehicular,DOUBLE PARKING/NO STANDING,False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,CHEVROLET,EQUINOX,BLACK,NaN,2020-05-16 23:38:00
2091116,60XX S STATE ST,41.881017,-87.627817,SU,34.0,black,female,NaN,NaN,NaN,NaN,vehicular,"LIGHT, TAIL LIGHTS REQUIRED",False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,NISSAN,SENTRA,BLACK,NaN,2020-05-16 23:40:00
2091117,26XX S STATE ST,41.881212,-87.628180,SU,31.0,black,male,NaN,NaN,NaN,NaN,vehicular,SPEED LIMIT 30MPH STR/15MPH ALLEY,False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,CHRYSLER/300,CHRYSLER/300,BLACK,NaN,2020-05-16 23:40:00
2091118,44XX N SAWYER AVE,41.898274,-87.707719,SU,44.0,hispanic,female,NaN,NaN,NaN,NaN,vehicular,HEADLIGHT TWO REQUIRED-MOTOR VEHICLE,False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,CHEVROLET,EXPRESS,HISPANIC,NaN,2020-05-16 23:47:00
2091119,18XX W AUGUSTA BLVD,41.899760,-87.664197,SU,47.0,hispanic,female,NaN,NaN,NaN,NaN,vehicular,BROKEN/INOPERABLE LAMPS,False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,TOYOTA,CAMRY,HISPANIC,NaN,2020-05-16 23:50:00

In [26]:
df.drop(columns=['geocode_source'],inplace=True)

/tmp/ipykernel_2766/1012908195.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns=['geocode_source'],inplace=True)

In [27]:
df

,location,lat,lng,subject_age,subject_race,subject_sex,officer_age,officer_race,officer_sex,officer_years_of_service,type,violation,arrest_made,citation_issued,outcome,contraband_found,contraband_drugs,contraband_weapons,contraband_alcohol,contraband_other,search_conducted,search_person,search_vehicle,vehicle_make,vehicle_model,raw_race,raw_driver_race,datetime
0,700 LINCOLN W,41.874405,-88.216690,23.0,black,male,NaN,white,male,17.0,vehicular,DRIVING ON SUSPENDED LICENSE,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,BLACK,NaN,2012-01-06 09:00:00
1,NaN,NaN,NaN,23.0,hispanic,male,NaN,white,male,2.0,vehicular,DRIVING/NEVER ISSUED LICENSE,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,HISPANIC,NaN,2012-01-01 00:00:00
2,0 NORTHWEST HWY & HILLSIDE RD S,42.146703,-88.119549,38.0,white,female,NaN,NaN,NaN,NaN,vehicular,DRIVING ON SUSPENDED LICENSE,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,WHITE,NaN,2012-01-01 01:00:00
3,108 LAMON AVE N,41.882072,-87.747829,35.0,black,male,34.0,black,male,8.0,vehicular,IVC - FAIL TO STOP/SIGNAL CROSSWALK,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,BLACK,NaN,2012-01-01 01:00:00
4,3451 177TH ST W,41.567987,-87.701027,20.0,black,male,NaN,NaN,NaN,NaN,vehicular,IVC - DRIVING 15-20 MPH ABOVE SPEED LIMIT,True,False,arrest,NaN,NaN,NaN,False,NaN,False,False,False,NaN,NaN,BLACK,NaN,2012-01-01 01:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2091115,37XX W MONTROSE AVE,41.959602,-87.824398,39.0,black,male,NaN,NaN,NaN,NaN,vehicular,DOUBLE PARKING/NO STANDING,False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,CHEVROLET,EQUINOX,BLACK,NaN,2020-05-16 23:38:00
2091116,60XX S STATE ST,41.881017,-87.627817,34.0,black,female,NaN,NaN,NaN,NaN,vehicular,"LIGHT, TAIL LIGHTS REQUIRED",False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,NISSAN,SENTRA,BLACK,NaN,2020-05-16 23:40:00
2091117,26XX S STATE ST,41.881212,-87.628180,31.0,black,male,NaN,NaN,NaN,NaN,vehicular,SPEED LIMIT 30MPH STR/15MPH ALLEY,False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,CHRYSLER/300,CHRYSLER/300,BLACK,NaN,2020-05-16 23:40:00
2091118,44XX N SAWYER AVE,41.898274,-87.707719,44.0,hispanic,female,NaN,NaN,NaN,NaN,vehicular,HEADLIGHT TWO REQUIRED-MOTOR VEHICLE,False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,CHEVROLET,EXPRESS,HISPANIC,NaN,2020-05-16 23:47:00
2091119,18XX W AUGUSTA BLVD,41.899760,-87.664197,47.0,hispanic,female,NaN,NaN,NaN,NaN,vehicular,BROKEN/INOPERABLE LAMPS,False,False,NaN,NaN,NaN,NaN,False,NaN,False,False,False,TOYOTA,CAMRY,HISPANIC,NaN,2020-05-16 23:50:00

In [31]:
df['subject_age']=df['subject_age'].astype('Int8')
df['officer_age']=df['officer_age'].astype('Int8')
df['officer_years_of_service']=df['officer_years_of_service'].astype('Int8')

/tmp/ipykernel_2766/2885025748.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['subject_age']=df['subject_age'].astype('Int8')
/tmp/ipykernel_2766/2885025748.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['officer_age']=df['officer_age'].astype('Int8')

TypeError: cannot safely cast non-equivalent float64 to int8

In [33]:
df['officer_years_of_service']=df['officer_years_of_service'].astype('Int8')

TypeError: cannot safely cast non-equivalent float64 to int8

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2091119 entries, 0 to 2091119
Data columns (total 28 columns):
 #   Column                    Dtype
---  ------                    -----
 0   location                  object
 1   lat                       float64
 2   lng                       float64
 3   subject_age               Int8
 4   subject_race              category
 5   subject_sex               category
 6   officer_age               Int8
 7   officer_race              category
 8   officer_sex               category
 9   officer_years_of_service  float64
 10  type                      category
 11  violation                 category
 12  arrest_made               bool
 13  citation_issued           bool
 14  outcome                   category
 15  contraband_found          object
 16  contraband_drugs          object
 17  contraband_weapons        object
 18  contraband_alcohol        bool
 19  contraband_other          object
 20  search_conducted          bool
 21  search_person             bool
 22  search_vehicle            bool
 23  vehicle_make              category
 24  vehicle_model             category
 25  raw_race                  object
 26  raw_driver_race           object
 27  datetime                  object
dtypes: Int8(2), bool(6), category(9), float64(3), object(8)
memory usage: 235.5+ MB

In [35]:
# 1. Convert to actual datetime objects
df['datetime'] = pd.to_datetime(df['datetime'])

# 2. Convert remaining contraband columns to nullable boolean
contraband_cols = ['contraband_found', 'contraband_drugs', 'contraband_weapons', 'contraband_other']
for col in contraband_cols:
    df[col] = df[col].astype('boolean')

# 3. Drop redundant raw demographic columns
df = df.drop(columns=['raw_race', 'raw_driver_race'])

/tmp/ipykernel_2766/3059908676.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['datetime'] = pd.to_datetime(df['datetime'])
/tmp/ipykernel_2766/3059908676.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype('boolean')
/tmp/ipykernel_2766/3059908676.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype('boolean')
/tmp/ipykernel_2766/3059908676.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype('boolean')
/tmp/ipykernel_2766/3059908676.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype('boolean')

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2091119 entries, 0 to 2091119
Data columns (total 26 columns):
 #   Column                    Dtype
---  ------                    -----
 0   location                  object
 1   lat                       float64
 2   lng                       float64
 3   subject_age               Int8
 4   subject_race              category
 5   subject_sex               category
 6   officer_age               Int8
 7   officer_race              category
 8   officer_sex               category
 9   officer_years_of_service  float64
 10  type                      category
 11  violation                 category
 12  arrest_made               bool
 13  citation_issued           bool
 14  outcome                   category
 15  contraband_found          boolean
 16  contraband_drugs          boolean
 17  contraband_weapons        boolean
 18  contraband_alcohol        bool
 19  contraband_other          boolean
 20  search_conducted          bool
 21  search_person             bool
 22  search_vehicle            bool
 23  vehicle_make              category
 24  vehicle_model             category
 25  datetime                  datetime64[ns]
dtypes: Int8(2), bool(6), boolean(4), category(9), datetime64[ns](1), float64(3), object(1)
memory usage: 155.7+ MB

In [37]:
df.isna().sum()

location                      74980
lat                          105264
lng                          105264
subject_age                  624048
subject_race                 652137
subject_sex                     851
officer_age                 2031912
officer_race                1318422
officer_sex                 1318422
officer_years_of_service    1320884
type                              1
violation                         1
arrest_made                       0
citation_issued                   0
outcome                     1258983
contraband_found            2078937
contraband_drugs            2078937
contraband_weapons          2078937
contraband_alcohol                0
contraband_other            2078937
search_conducted                  0
search_person                     0
search_vehicle                    0
vehicle_make                 832136
vehicle_model                832136
datetime                          0
dtype: int64

In [56]:
df.drop(columns='officer_age',inplace=True)

KeyError: "['officer_age'] not found in axis"

<class 'pandas.core.frame.DataFrame'>
Index: 2091119 entries, 0 to 2091119
Data columns (total 25 columns):
 #   Column                    Dtype
---  ------                    -----
 0   location                  object
 1   lat                       float64
 2   lng                       float64
 3   subject_age               Int8
 4   subject_race              category
 5   subject_sex               category
 6   officer_race              category
 7   officer_sex               category
 8   officer_years_of_service  float64
 9   type                      category
 10  violation                 category
 11  arrest_made               bool
 12  citation_issued           bool
 13  outcome                   category
 14  contraband_found          boolean
 15  contraband_drugs          boolean
 16  contraband_weapons        boolean
 17  contraband_alcohol        bool
 18  contraband_other          boolean
 19  search_conducted          bool
 20  search_person             bool
 21  search_vehicle            bool
 22  vehicle_make              category
 23  vehicle_model             category
 24  datetime                  datetime64[ns]
dtypes: Int8(1), bool(6), boolean(4), category(9), datetime64[ns](1), float64(3), object(1)
memory usage: 151.7+ MB

In [57]:
df.to_csv('stops.csv',index=False)